objects:
  - owner: System
    owner_uuid: '%identity.system.uuid%'
    assignee: System
    assignee_uuid: '%identity.system.uuid%'
    permissions:
      - scope: generic
        key: entity
        attributes: [BROWSE, READ, EDIT, ADD, DELETE]
      - scope: generic
        key: property
        attributes: [BROWSE, READ, EDIT]
      - scope: generic
        key: generic
        attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]

  - owner: BusinessUnit
    owner_uuid: '%business_unit.administration.uuid%'
    assignee: Staff
    assignee_uuid: '%identity.admin.uuid%'
    permissions:
      - scope: generic
        key: entity
        attributes: [BROWSE, READ, EDIT, ADD, DELETE]
      - scope: generic
        key: property
        attributes: [BROWSE, READ, EDIT]
      - scope: generic
        key: generic
        attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]

prototype:
  owner: ~
  owner_uuid: ~
  assignee: ~
  assignee_uuid: ~
  permissions: []
  tenant: '%tenant.uuid%'
