objects:
  - owner: System
    owner_uuid: '%identity.system.uuid%'
    assignee: System
    assignee_uuid: '%identity.system.uuid%'
    permissions:
      - scope:
          type: generic
        key: entity
        attributes: [BROWSE, READ, EDIT, ADD, DELETE]
      - scope:
          type: generic
        key: property
        attributes: [BROWSE, READ, EDIT]
      - scope:
          type: generic
        key: generic
        attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]

  - owner: BusinessUnit
    owner_uuid: '%business_unit.administration.uuid%'
    assignee: Role
    assignee_uuid: '%role.administrator.uuid%'
    permissions:
      - scope:
          type: owner
          entity: BusinessUnit
          entity_uuid: ~
        key: entity
        attributes: [BROWSE, READ, EDIT, ADD, DELETE]
      - scope:
          type: owner
          entity: BusinessUnit
          entity_uuid: ~
        key: property
        attributes: [BROWSE, READ, EDIT]
      - scope:
          type: generic
        key: generic
        attributes: [BROWSE, READ, EDIT, ADD, DELETE, EXECUTE]

prototype:
  owner: ~
  owner_uuid: ~
  assignee: ~
  assignee_uuid: ~
  permissions: []
  tenant: '%tenant.uuid%'
