sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.11.2
  JWT_PASS_PHRASE: 00ix4gk15tgvh6hl7z8nlj0r2xvlxczj

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - openssl genrsa -out var/jwt/key -aes256 -passout pass:${JWT_PASS_PHRASE} 4096
  - openssl rsa -pubout -in var/jwt/key -out var/jwt/key.pub -passin pass:${JWT_PASS_PHRASE}

script:
  - docker network create dsproxy_default
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm php composer install --prefer-dist --no-progress --no-suggest --no-interaction
#  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm php bin/console security:check
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm php vendor/bin/behat
