sudo: required

env:
  API_ENV: test
  API_SECRET: byzxl36nl289x6yu71hdie2euf19vm3r
  API_JWT_PASS_PHRASE: 00ix4gk15tgvh6hl7z8nlj0r2xvlxczj
  API_ENCRYPTION: def00000b66cdea17be03154351b285554884f1cba050541781f535bce839d31e315a82771d5dc5c32a8634ba1d7831ce5f1ec0a29e4a17344216eb038745acd63d3149f
  API_SYSTEM_USERNAME: system
  API_SYSTEM_PASSWORD: system

services:
  - docker

before_install:
  - openssl genrsa -out api/config/jwt/key -aes256 -passout pass:${API_JWT_PASS_PHRASE} 4096
  - openssl rsa -pubout -in api/config/jwt/key -out api/config/jwt/key.pub -passin pass:${API_JWT_PASS_PHRASE}

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml build
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm php composer install --prefer-dist --no-progress --no-suggest --no-interaction
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm php php bin/console security:check
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm php vendor/bin/behat
