version: '3.4'

services:
  php:
    environment:
      APP_ENV: test
    volumes:
      - ${DIRECTORY}/api:/srv/api:rw,cached

  api:
    volumes:
      - ${DIRECTORY}/api/public:/srv/api/public:ro

  mock_discovery:
    image: rodolpheche/wiremock:2.19.0-alpine
    volumes:
      - ${DIRECTORY}/mock/discovery:/home/wiremock:rw
    networks:
      default:
        aliases:
          - microservice_mock_discovery
