version: '3.1'

services:
  adminer:
    image: adminer:4-standalone
    environment:
      VIRTUAL_HOST: '${ADMINER_VIRTUAL_HOST}'
    links:
      - database:services_database

  rebrow:
    image: marian/rebrow
    environment:
      VIRTUAL_HOST: '${REBROW_VIRTUAL_HOST}'
    links:
      - redis:services_redis

  php:
    environment:
      SYMFONY_ENV: dev
    extra_hosts:
      - 'api.assets.lab.ds:${PROXY_HOST}'
      - 'api.authentication.lab.ds:${PROXY_HOST}'
      - 'api.camunda.lab.ds:${PROXY_HOST}'
      - 'api.cases.lab.ds:${PROXY_HOST}'
      - 'api.cms.lab.ds:${PROXY_HOST}'
      - 'api.discovery.lab.ds:${PROXY_HOST}'
      - 'api.formio.lab.ds:${PROXY_HOST}'
      - 'api.identities.lab.ds:${PROXY_HOST}'
      - 'api.interactions.lab.ds:${PROXY_HOST}'
      - 'api.logs.lab.ds:${PROXY_HOST}'
      - 'api.records.lab.ds:${PROXY_HOST}'
      - 'api.services.lab.ds:${PROXY_HOST}'
      - 'api.tasks.lab.ds:${PROXY_HOST}'
      - 'api.tenants.lab.ds:${PROXY_HOST}'
      - 'api.topics.lab.ds:${PROXY_HOST}'
