version: '3.1'

services:
  php:
    environment:
      SYMFONY_ENV: dev
    extra_hosts:
      - 'api.assets.lab.ds:${PROXY_HOST}'
      - 'api.authentication.lab.ds:${PROXY_HOST}'
      - 'api.camunda.lab.ds:${PROXY_HOST}'
      - 'api.cases.lab.ds:${PROXY_HOST}'
      - 'api.cms.lab.ds:${PROXY_HOST}'
      - 'api.discovery.lab.ds:${PROXY_HOST}'
      - 'api.formio.lab.ds:${PROXY_HOST}'
      - 'api.forms.lab.ds:${PROXY_HOST}'
      - 'api.identities.lab.ds:${PROXY_HOST}'
      - 'api.records.lab.ds:${PROXY_HOST}'
      - 'api.services.lab.ds:${PROXY_HOST}'
      - 'api.tasks.lab.ds:${PROXY_HOST}'
      - 'api.tenants.lab.ds:${PROXY_HOST}'

  database_ui:
    image: adminer:4-standalone
    environment:
      SERVICE_8080_ID: '${COMPOSE_PROJECT_NAME}_database_ui_http'
      SERVICE_8080_NAME: '${COMPOSE_PROJECT_NAME}_database_ui_http'
      SERVICE_8080_TAGS: 'proxy.enable=true,proxy.tags=external,proxy.frontend.entryPoints=http,proxy.frontend.rule=Host:${DATABASE_UI_HOST}'
    links:
      - database:services_database

  cache_ui:
    image: marian/rebrow
    environment:
      SERVICE_5001_ID: '${COMPOSE_PROJECT_NAME}_cache_ui_http'
      SERVICE_5001_NAME: '${COMPOSE_PROJECT_NAME}_cache_ui_http'
      SERVICE_5001_TAGS: 'proxy.enable=true,proxy.tags=external,proxy.frontend.entryPoints=http,proxy.frontend.rule=Host:${CACHE_UI_HOST}'
    links:
      - cache:services_cache
