version: '3.1'

services:
    php:
        build: .
        environment:
            SYMFONY_ENV: test
        extra_hosts:
            - 'api.assets.ci.ds:${PROXY_HOST}'
            - 'api.authentication.ci.ds:${PROXY_HOST}'
            - 'api.camunda.ci.ds:${PROXY_HOST}'
            - 'api.cases.ci.ds:${PROXY_HOST}'
            - 'api.cms.ci.ds:${PROXY_HOST}'
            - 'api.discovery.ci.ds:${PROXY_HOST}'
            - 'api.formio.ci.ds:${PROXY_HOST}'
            - 'api.identities.ci.ds:${PROXY_HOST}'
            - 'api.interactions.ci.ds:${PROXY_HOST}'
            - 'api.logs.ci.ds:${PROXY_HOST}'
            - 'api.records.ci.ds:${PROXY_HOST}'
            - 'api.services.ci.ds:${PROXY_HOST}'
            - 'api.tasks.ci.ds:${PROXY_HOST}'
            - 'api.topics.ci.ds:${PROXY_HOST}'
