ds_config:
  configs:
    - { key: app.bpm.variables.api_url,               encrypt: false,  title: app.configs.bpm.variables.api_url              }
    - { key: app.bpm.variables.api_user,              encrypt: false,  title: app.configs.bpm.variables.api_user             }
    - { key: app.bpm.variables.api_key,               encrypt: false,  title: app.configs.bpm.variables.api_key              }
    - { key: app.bpm.variables.service_uuid,          encrypt: false,  title: app.configs.bpm.variables.service_uuid         }
    - { key: app.bpm.variables.scenario_uuid,         encrypt: false,  title: app.configs.bpm.variables.scenario_uuid        }
    - { key: app.bpm.variables.scenario_custom_data,  encrypt: false,  title: app.configs.bpm.variables.scenario_custom_data }
    - { key: app.bpm.variables.identity,              encrypt: false,  title: app.configs.bpm.variables.identity             }
    - { key: app.bpm.variables.identity_uuid,         encrypt: false,  title: app.configs.bpm.variables.identity_uuid        }
    - { key: app.bpm.variables.submission_uuid,       encrypt: false,  title: app.configs.bpm.variables.submission_uuid      }
    - { key: app.bpm.variables.start_data,            encrypt: false,  title: app.configs.bpm.variables.start_data           }
