parameters:
  locale: en

framework:
  secret: '%env(APP_SECRET)%'
  default_locale: '%locale%'
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - '%locale%'
  #csrf_protection: ~
  #http_method_override: true
  session:
    handler_id: ~
  #esi: ~
  #fragments: ~
  php_errors:
    log: true
  cache:
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost
  validation:
    email_validation_mode: html5
#  workflows:
#    submission_state:
#      type: state_machine
#      marking_store:
#        type: single_state
#        arguments:
#          - state
#      supports:
#        - App\Entity\Submission
#      places:
#        - !php/const:App\Entity\Submission::STATE_DRAFT
#        - !php/const:App\Entity\Submission::STATE_SUBMITTED
#        - !php/const:App\Entity\Submission::STATE_TRANSFERRED
#      transitions:
#        submit:
#          from: [!php/const:App\Entity\Submission::STATE_DRAFT]
#          to: [!php/const:App\Entity\Submission::STATE_SUBMITTED]
#        transfer:
#          from: [!php/const:App\Entity\Submission::STATE_SUBMITTED]
#          to: [!php/const:App\Entity\Submission::STATE_TRANSFERRED]
