parameters:
  locale: en

framework:
  secret: '%env(APP_SECRET)%'
  default_locale: '%locale%'
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - '%locale%'
  #csrf_protection: ~
  #http_method_override: true
  session:
    handler_id: ~
  #esi: ~
  #fragments: ~
  php_errors:
    log: true
  cache:
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost
  validation:
    email_validation_mode: html5
