imports:
  - { resource: ../config.yml }

parameters:
  cache_prefix: dev:

framework:
  router:
    resource: '%kernel.root_dir%/config/dev/routing.yml'
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    stream:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      formatter: app.monolog.formatter.json
    console:
      type: console
      channels: [!event, !doctrine]

api_platform:
  enable_swagger: true
  enable_swagger_ui: true
