services:
    ds.entity.event_listener.uuid:
        class: Ds\Component\Entity\EventListener\UuidListener
        autowire: true
        tags:
            - { name: doctrine.event_listener, event: prePersist }
