api:
    resource: .
    type: api_platform

ds_health:
    resource: '@DsHealthBundle/Resources/config/routing.yml'

ds_security:
    resource: '@DsSecurityBundle/Resources/config/routing.yml'

app_action:
    resource: '@AppBundle/Action/'
    type: annotation
