services:
    ds_bpm_camunda.service.process_definition:
        parent: ds_bpm.service
        class: '%ds_bpm_camunda.service.process_definition.class%'

    ds_bpm_camunda.service.process_instance:
        parent: ds_bpm.service
        class: '%ds_bpm_camunda.service.process_instance.class%'

    ds_bpm_camunda.service.task:
        parent: ds_bpm.service
        class: '%ds_bpm_camunda.service.task.class%'
