monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_404s:
        - ^/
    nested:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      formatter: Monolog\Formatter\JsonFormatter
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine']
      formatter: Monolog\Formatter\JsonFormatter
    deprecation:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
      formatter: Monolog\Formatter\JsonFormatter
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ['php']
      formatter: Monolog\Formatter\JsonFormatter
