ds_security:
    acl:
        permissions:
            service:            { entity: Ds\Bundle\ServiceBundle\Entity\Service, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            service_field:      { field:  Ds\Bundle\ServiceBundle\Entity\Service.*, attributes: [BROWSE, READ, EDIT] }
