parameters:
    _category: Ds\Bundle\ServiceBundle\Entity\Category
    _service: Ds\Bundle\ServiceBundle\Entity\Service
    _scenario: Ds\Bundle\ServiceBundle\Entity\Scenario
    _submission: Ds\Bundle\ServiceBundle\Entity\Submission

ds_security:
    permissions:
        category:                 { title: Category,      entity: '%_category%',                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        category_field:           { title: All Fields,    field:  '%_category%.*',              attributes: [BROWSE, READ, EDIT] }
        category_id:              { title: ID,            field:  '%_category%.id',             attributes: [BROWSE, READ, EDIT] }
        category_uuid:            { title: UUID,          field:  '%_category%.uuid',           attributes: [BROWSE, READ, EDIT] }
        category_created_at:      { title: Created At,    field:  '%_category%.createdAt',      attributes: [BROWSE, READ, EDIT] }
        category_updated_at:      { title: Updated At,    field:  '%_category%.updatedAt',      attributes: [BROWSE, READ, EDIT] }
        category_deleted_at:      { title: Deleted At,    field:  '%_category%.deletedAt',      attributes: [BROWSE, READ, EDIT] }
        category_owner:           { title: Owner,         field:  '%_category%.owner',          attributes: [BROWSE, READ, EDIT] }
        category_owner_uuid:      { title: Owner UUID,    field:  '%_category%.ownerUuid',      attributes: [BROWSE, READ, EDIT] }
        category_title:           { title: Title,         field:  '%_category%.title',          attributes: [BROWSE, READ, EDIT] }
        category_description:     { title: Description,   field:  '%_category%.description',    attributes: [BROWSE, READ, EDIT] }
        category_presentation:    { title: Presentation,  field:  '%_category%.presentation',   attributes: [BROWSE, READ, EDIT] }

        service:                  { title: Service,       entity: '%_service%',                 attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        service_field:            { title: All Fields,    field:  '%_service%.*',               attributes: [BROWSE, READ, EDIT] }
        service_id:               { title: ID,            field:  '%_service%.id',              attributes: [BROWSE, READ, EDIT] }
        service_uuid:             { title: UUID,          field:  '%_service%.uuid',            attributes: [BROWSE, READ, EDIT] }
        service_created_at:       { title: Created At,    field:  '%_service%.createdAt',       attributes: [BROWSE, READ, EDIT] }
        service_updated_at:       { title: Updated At,    field:  '%_service%.updatedAt',       attributes: [BROWSE, READ, EDIT] }
        service_deleted_at:       { title: Deleted At,    field:  '%_service%.deletedAt',       attributes: [BROWSE, READ, EDIT] }
        service_owner:            { title: Owner,         field:  '%_service%.owner',           attributes: [BROWSE, READ, EDIT] }
        service_owner_uuid:       { title: Owner UUID,    field:  '%_service%.ownerUuid',       attributes: [BROWSE, READ, EDIT] }
        service_title:            { title: Title,         field:  '%_service%.title',           attributes: [BROWSE, READ, EDIT] }
        service_description:      { title: Description,   field:  '%_service%.description',     attributes: [BROWSE, READ, EDIT] }
        service_presentation:     { title: Presentation,  field:  '%_service%.presentation',    attributes: [BROWSE, READ, EDIT] }

        scenario:                 { title: Scenario,      entity: '%_scenario%',                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        scenario_field:           { title: All Fields,    field:  '%_scenario%.*',              attributes: [BROWSE, READ, EDIT] }
        scenario_id:              { title: ID,            field:  '%_scenario%.id',             attributes: [BROWSE, READ, EDIT] }
        scenario_uuid:            { title: UUID,          field:  '%_scenario%.uuid',           attributes: [BROWSE, READ, EDIT] }
        scenario_created_at:      { title: Created At,    field:  '%_scenario%.createdAt',      attributes: [BROWSE, READ, EDIT] }
        scenario_updated_at:      { title: Updated At,    field:  '%_scenario%.updatedAt',      attributes: [BROWSE, READ, EDIT] }
        scenario_deleted_at:      { title: Deleted At,    field:  '%_scenario%.deletedAt',      attributes: [BROWSE, READ, EDIT] }
        scenario_owner:           { title: Owner,         field:  '%_scenario%.owner',          attributes: [BROWSE, READ, EDIT] }
        scenario_owner_uuid:      { title: Owner UUID,    field:  '%_scenario%.ownerUuid',      attributes: [BROWSE, READ, EDIT] }
        scenario_type:            { title: Type,          field:  '%_scenario%.type',           attributes: [BROWSE, READ, EDIT] }
        scenario_title:           { title: Title,         field:  '%_scenario%.title',          attributes: [BROWSE, READ, EDIT] }
        scenario_description:     { title: Description,   field:  '%_scenario%.description',    attributes: [BROWSE, READ, EDIT] }
        scenario_presentation:    { title: Presentation,  field:  '%_scenario%.presentation',   attributes: [BROWSE, READ, EDIT] }
        scenario_data:            { title: Data,          field:  '%_scenario%.data',           attributes: [BROWSE, READ, EDIT] }

        submission:               { title: Submission,    entity: '%_submission%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        submission_field:         { title: All Fields,    field:  '%_submission%.*',            attributes: [BROWSE, READ, EDIT] }
        submission_id:            { title: ID,            field:  '%_submission%.id',           attributes: [BROWSE, READ, EDIT] }
        submission_uuid:          { title: UUID,          field:  '%_submission%.uuid',         attributes: [BROWSE, READ, EDIT] }
        submission_created_at:    { title: Created At,    field:  '%_submission%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        submission_updated_at:    { title: Updated At,    field:  '%_submission%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        submission_deleted_at:    { title: Deleted At,    field:  '%_submission%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        submission_owner:         { title: Owner,         field:  '%_submission%.owner',        attributes: [BROWSE, READ, EDIT] }
        submission_owner_uuid:    { title: Owner UUID,    field:  '%_submission%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
        submission_identity:      { title: Identity,      field:  '%_submission%.identity',     attributes: [BROWSE, READ, EDIT] }
        submission_identity_uuid: { title: Identity UUID, field:  '%_submission%.identityUuid', attributes: [BROWSE, READ, EDIT] }
        submission_data:          { title: Data,          field:  '%_submission%.data',         attributes: [BROWSE, READ, EDIT] }
        submission_state:         { title: State,         field:  '%_submission%.state',        attributes: [BROWSE, READ, EDIT] }

ds_service:
    services:
        formio:
            url: ~
