ds_bpm:
    variables:
        api_url: _api_url
        api_user: _api_user
        api_key: _api_key
        service_uuid: _service_uuid
        scenario_uuid: _scenario_uuid
        identity: _identity
        identity_uuid: _identity_uuid
        submission_uuid: _submission_uuid
        none_start_event_form_data: _none_start_event_form_data
        localization: _localization
        user_task_form_data: _user_task_form_data
        error: _error
