services:
    ds_bpm.http.client:
        class: GuzzleHttp\Client

    ds_bpm.service:
        abstract: true
        arguments:
            - "@ds_bpm.http.client"

    ds_bpm.collection.api:
        class: Ds\Bundle\BpmBundle\Collection\ApiCollection

    ds_bpm.api.factory:
        class: Ds\Bundle\BpmBundle\Api\Factory
        arguments:
            - "@ds_bpm.collection.api"
            - "@ds_config.service.config"
