services:
    ds_formio.http.client:
        class: GuzzleHttp\Client

    ds_formio.service:
        abstract: true
        arguments:
            - '@ds_formio.http.client'

    ds_formio.service.form:
        parent: ds_formio.service
        class: Ds\Component\Formio\Service\FormService

    ds_formio.api:
        class: Ds\Component\Formio\Api\Api
        arguments:
            - '@ds_formio.http.client'
