services:
    app.service.service:
        class: AppBundle\Service\ServiceService
        parent: ds_entity.service.entity

    app.service.category:
        class: AppBundle\Service\CategoryService
        parent: ds_entity.service.entity

    app.service.scenario:
        class: AppBundle\Service\ScenarioService
        parent: ds_entity.service.entity
        arguments:
            - '@ds_bpm.api.factory'
            - '@ds_bpm.resolver.bpm'
            - '@ds_formio.api'
            - '@ds_config.service.config'

    app.service.submission:
        class: AppBundle\Service\SubmissionService
        parent: ds_entity.service.entity
        arguments:
            - '@app.service.scenario'
            - '@ds_formio.api'
            - '@ds_config.service.config'
