services:
    app.service.service:
        class: AppBundle\Service\ServiceService
        parent: ds_entity.service.entity

    app.service.category:
        class: AppBundle\Service\CategoryService
        parent: ds_entity.service.entity

    app.service.scenario:
        class: AppBundle\Service\ScenarioService
        parent: ds_entity.service.entity
        arguments:
            - '@ds_api.factory'
            - '@ds_resolver.collection.resolver'

    app.service.submission:
        class: AppBundle\Service\SubmissionService
        parent: ds_entity.service.entity
        arguments:
            - '@app.service.scenario'
            - '@ds_api.factory'
