<?php

return [
    ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Ds\Component\Acl\DsAclBundle::class => ['all' => true],
    Ds\Component\Api\DsApiBundle::class => ['all' => true],
    Ds\Component\Bpm\DsBpmBundle::class => ['all' => true],
    Ds\Component\Container\DsContainerBundle::class => ['all' => true],
    Ds\Component\Config\DsConfigBundle::class => ['all' => true],
    Ds\Component\Debug\DsDebugBundle::class => ['dev' => true, 'test' => true],
    Ds\Component\Discovery\DsDiscoveryBundle::class => ['all' => true],
    Ds\Component\Encryption\DsEncryptionBundle::class => ['all' => true],
    Ds\Component\Entity\DsEntityBundle::class => ['all' => true],
    Ds\Component\Exception\DsExceptionBundle::class => ['all' => true],
    Ds\Component\Filter\DsFilterBundle::class => ['all' => true],
    Ds\Component\Form\DsFormBundle::class => ['all' => true],
    Ds\Component\Health\DsHealthBundle::class => ['all' => true],
    Ds\Component\Identity\DsIdentityBundle::class => ['all' => true],
    Ds\Component\Locale\DsLocaleBundle::class => ['all' => true],
    Ds\Component\Log\DsLogBundle::class => ['all' => true],
    Ds\Component\Metadata\DsMetadataBundle::class => ['all' => true],
    Ds\Component\Parameter\DsParameterBundle::class => ['all' => true],
    Ds\Component\Resolver\DsResolverBundle::class => ['all' => true],
    Ds\Component\Security\DsSecurityBundle::class => ['all' => true],
    Ds\Component\Security\Test\DsSecurityTestBundle::class => ['test' => true],
    Ds\Component\Statistic\DsStatisticBundle::class => ['all' => true],
    Ds\Component\System\DsSystemBundle::class => ['all' => true],
    Ds\Component\System\Test\DsSystemTestBundle::class => ['test' => true],
    Ds\Component\Tenant\DsTenantBundle::class => ['all' => true],
    Ds\Component\Translation\DsTranslationBundle::class => ['all' => true],
    Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
];
