parameters:
  locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: ../src/{Controller,Fixture,Repository,Service}

  App\Controller\:
    resource: ../src/Controller
    tags: [controller.service_arguments]

  App\Controller\Scenario\Forms\TranslationController:
    arguments:
      - '@App\Service\ScenarioService'
      - '@request_stack'
      - '%locale%'

  App\Fixture\:
    resource: ../src/Fixture
    tags: [doctrine.fixture.orm]

  App\Validator\Constraints\Scenario\Config\ValidValidator:
    tags:
      - { name: validator.constraint_validator }
