parameters:
  locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: ../src/{Fixtures}

  App\Controller\:
    resource: ../src/Controller
    tags: [controller.service_arguments]

  App\Fixtures\:
    resource: ../src/Fixtures
    tags: [doctrine.fixture.orm]
