parameters:
  locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: ../src/{Controller,EventListener,Fixture,Repository,Service}

  App\Controller\:
    resource: ../src/Controller
    tags: [controller.service_arguments]

  App\Controller\Scenario\Forms\TranslationController:
    arguments:
      - '@App\Service\ScenarioService'
      - '@request_stack'
      - '%locale%'

  App\EventListener\Submission\Validation\DataListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: kernelView, priority: 64 }

  App\EventListener\Submission\OwnerListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Submission, event: prePersist }

  App\EventListener\Submission\Transfer\BpmListener:
    tags:
      - { name: doctrine.orm.entity_listener, entity: App\Entity\Submission, event: postPersist }

  App\Fixture\:
    resource: ../src/Fixture
    tags: [doctrine.fixture.orm]

  App\Validator\Constraints\Scenario\Config\ValidValidator:
    tags:
      - { name: validator.constraint_validator }
