services:
    ds_bpm.resolver.bpm:
        class: '%ds_bpm.resolver.bpm.class%'
        arguments:
            - '@ds_bpm.api.factory'
        tags:
            - { name: ds_resolver.resolver, alias: ds.context.bpm }

    ds_bpm.resolver.task:
        class: '%ds_bpm.resolver.task.class%'
        arguments:
            - '@ds_bpm.api.factory'
        tags:
            - { name: ds_resolver.resolver, alias: ds.bpm.task }

    ds_bpm.resolver.tasks:
        class: '%ds_bpm.resolver.tasks.class%'
        arguments:
            - '@ds_bpm.api.factory'
        tags:
            - { name: ds_resolver.resolver, alias: ds.bpm.tasks }
