imports:
    - { resource: ../config.yml }

doctrine:
    orm:
        second_level_cache:
            enabled: true

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
